#!/bin/bash
set -e

docker-compose -f docker-compose.test.yml build
docker-compose -f docker-compose.test.yml run web python manage.py collectstatic --no-input
docker-compose -f docker-compose.test.yml run --rm web pytest
